### ISSUE TITLE
Not executed {foo} resets concatenation sum

### ISSUE THREAD

**Issue by PeteyPii** [DJMcMayhem/Brain-Flak#26]
The program `((){{}})` correctly returns 2 when the input is 1 but 0 0 when the input is 0. I expect it to be 1 0 since {{}} should evaluate to 0. I get the correct output if the () comes after the {{}}.

**Comment by Wheatwizard** [comment]
This bug has been hanging around for a while and has been "fixed" at least [once](https://github.com/DJMcMayhem/Brain-Flak/commit/7be2ae82c3908e0793fc9392d4bf8fbdf64cd51b).

**Comment by Wheatwizard** [comment]
You may be on an older version of Brain-Flak.  This issue has been resolved.

**Comment by PeteyPii** [comment]
Ah, I'm using http://brain-flak.tryitonline.net/ so that could be it!

**Comment by Wheatwizard** [comment]
Oh yeah that will do it.  That version is not always up to date.  Sorry about that.

**Comment by DJMcMayhem** [comment]
Yeah, that would seem to explain it. I can update the try it online link, but there are a couple minor improvements I'd like to implement before doing so, for example integer wraparound and a way to handle ascii (like the way brainfuck does). Neither of those should take super long, so the TIO link should be updated fairly soon.

The TIO site is hosted by someone else, so I try not to pester him to update it super often, only when I have a milestone I like.
