### ISSUE TITLE
Loops not beginning at the start of the program do not work properly when being passed over

### ISSUE THREAD

**Issue by 1000000000** [DJMcMayhem/Brain-Flak#3]
If a loop executes zero times then the interpreter finds the corresponding closing brace and moves the read head to the position of ([location of close brace] - [location of open brace]) (roughly).

**Comment by DJMcMayhem** [comment]
Could you provide an example of some brainflak code that does this?

**Comment by 1000000000** [comment]
`(<(())>){(())}` should run fine and terminate with 0 and 1 on the stack but instead the interpreter throws an error.

**Comment by DJMcMayhem** [comment]
This is now working as expected. Thanks for fixing it!
