### ISSUE TITLE
Update debug flags for debugging ASCII programs

### ISSUE THREAD

**Issue by 1000000000** [DJMcMayhem/Brain-Flak#38]
Now that we have ASCII support for Brain-Flak it would be a good idea (as @Wheatwizard suggested to me) to add support for ASCII debugging by retooling existing debug flags when possible and adding new debug flags when necessary.

The debug flags that would need to be modified or have ASCII equivalents created are:
- `#dv`
- `#dc`
- `#dl`
- `#dr`
- `#df`

For naming any new debug flags that need to be created I suggest simply replace the 'd' with an 'a' in the corresponding decimal debug flag.

**Comment by Wheatwizard** [comment]
Added with cc45d821207c37e49350795bc1f8a0a86f84daa7
