### ISSUE TITLE
I/O order specifications

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#42]
Lately we have had some changes in the way that input and output is ordered.  We do not have a specification for the way that input and output is handled and I think we should.

**Comment by Wheatwizard** [comment]
The two things that I find important in I/O are the following
-  The empty program does not change the order
-  The top of the stack is printed first at the end of the program

These two requirements unambiguously force a I/O order.   Thus I propose we use this order.

**Comment by DJMcMayhem** [comment]
This seems wrapped up as of V1.0.1 to me, so I'm gonna close this issue.
