### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#44]
Lots of programming languages have cool logos.

Like this:
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Haskell-Logo.svg/1280px-Haskell-Logo.svg.png" width="100"/>
or this:
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Elm_logo.svg/1024px-Elm_logo.svg.png" width="100">

Maybe we should make one for Brain-Flak.  There is not much of a point to having a logo but I thought it might be fun to come up with one.

**Comment by Wheatwizard** [comment]
Here is a mockup for one idea I had:
![mockup](http://i.imgur.com/ukeB3nH.png)

I don't know if I really like it that much but I thought I'd get the ball rolling.

**Comment by 1000000000** [comment]
That logo might be a bit big, but a logo could be fun. I don't see any reason not to have a logo.

**Comment by Wheatwizard** [comment]
Here's a smaller version:
![Smaller Logo](http://i.imgur.com/419ozEk.png)

**Comment by Wheatwizard** [comment]
I think we are done discussing this.
