### ISSUE TITLE
Debug Flag Documentation

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#46]
It just occurred to me that we have no documentation on debug flags whatsoever.  Where should we add them?  We could add to the wiki but that might be a bit hard to find.  We could add them to the README but the README already has quite a lot going on.

**Comment by DJMcMayhem** [comment]
There's actually a couple other things I've been meaning to document. 
- Input modes
- Pushing a zero changes the value of `[]` (Martin pointed out that this was a little bit confusing to have explicit zeros)

**Comment by Wheatwizard** [comment]
Oh god, if we could get rid of explicit zeros it would make some things easier but a lot of things a lot harder.  I think that is a very big and perhaps contentious change.

**Comment by DJMcMayhem** [comment]
I think explicit zeroes are fine, they should just be explicitly mentioned in the docs.

**Comment by Wheatwizard** [comment]
`-H` will provide documentation for the time being.
