### ISSUE TITLE
Brain-Flak debug flags

### ISSUE THREAD

**Issue by 1000000000** [DJMcMayhem/Brain-Flak#6]
For whatever purpose, either hunting down errors in your brain-flak code or for trying to pin down a bug in the interpreter a debugger would be very useful. This has been touched upon elsewhere so I figured it would be a good idea to have a place to discuss the idea.

From @DJMcMayhem on the subject of the debugger

> I don't know what that will look like, but it will probably be a CLI flag (probably `-d`) and some commands to display
> - The active stack
> - A specific stack
> - The result of a function call
> 
> and a way to pause for user input, as well as maybe some others.

**Comment by 1000000000** [comment]
I have pushed a version of the program where most of the interpreter's functionality has been refactored into its own class. It is missing @Wheatwizard's changes for the moment.

**Comment by DJMcMayhem** [comment]
Haha, we happened to make changes at the same time. That might make it really hard to merge the two back together.

**Comment by DJMcMayhem** [comment]
We should setup a brain-flak chatroom so we can talk about potential changes faster than over commenting. I can set one up on stackoverflow. Do you have an account there?

**Comment by 1000000000** [comment]
Yup, same username as on Github

**Comment by DJMcMayhem** [comment]
Here you go: http://chat.stackexchange.com/rooms/41599/brain-flak

**Comment by 1000000000** [comment]
Completed by pull request #15
