### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#65]
As of 2c9a960f47af0b3ce0535ce8a20c77e85f5d45a2 I have generalized the interpreter so that it would be easy to add additional similar languages so that they could be run with all the fancy features of the Ruby interpreter.

So the question is, do we want to support additional existing languages?  If so which ones do we want to support.

Here is a complete<sup><sup>[citation needed]</sup></sup> list of Brain-Flak derivatives we might support:

 - Brain-Flak Classic
 - Miniflak
 - Brainflueue
 - Fλak
 - Flakcats

**Comment by Wheatwizard** [comment]
I think we should support some additional languages.

My opinion is that we should add support for Classic, Miniflak and Brain-Flueue.   These three are the most similar to Vanilla Brain-Flak and both Classic and Miniflak lack their own interpreters.  The other two are too different from Brain-Flak to be bundled into the Brain-Flak interpreter.

**Comment by DJMcMayhem** [comment]
I think that sounds good. I would have said the exact same thing about Classic and Mini-flak. Those two in particular will be nice to have hosted on TIO without actually needing to add a new interpreter. I'm not sure about Brain-flueue though. I've actually never used it before, so I'm not sure how different or useful it is. But, if you think it's worth it, I'll leave it up to you.

We do need to think about which flags to use though. Some of them are pretty obvious:

 - `-m`: Mini-flak
 - `-q`: Brain-Flueue ('q' for 'queue')

That just leaves classic. I'm not really sure what to do for that. `-c` is the obvious choice, but that's already claimed by the ASCII option. I suppose we could do `-C`, but this might be a little bit confusing.

**Comment by ConorOBrien-Foxx** [comment]
`-o` for original? Or `-a` for "alpha"/first? (I don't know the flags already present)

**Comment by Wheatwizard** [comment]
I was going to add a `--mode=` flag instead of giving each version its own flag.
You would run it with `brainflak --mode=classic ...` for classic mode.
