### ISSUE TITLE
Comment your code?

### ISSUE THREAD

**Issue by ckjbgames** [DJMcMayhem/Brain-Flak#66]
Would you please add some comments to your code? I am trying to port this to C++, but I do not know Ruby.
Thanks.

**Comment by Wheatwizard** [comment]
While the lack of comments is certainly an issue I recommend taking a look at [CraneFlak](https://github.com/Flakheads/CraneFlak) or [Crain-Flak++](https://github.com/Flakheads/Crain-flak-plus-plus) if you are trying to make a C++ port.

**Comment by ckjbgames** [comment]
I am making it with my own stack class.
