### ISSUE TITLE
Cycle counting

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#77]
I noticed some strangeness with cycle counting and the `@cy` flag.  Currently skipped loops count as a cycle.  For example the debug output of:

    {()}

[Try it online!][TIO-j3xkpv79]

is:

    Cycles:
    1
    Program:
    {()}
        ^
    Chararacter 5
    Stack:  
    ^

This in my opinion doesn't make a ton of sense, every loop costs 2 cycles normally (plus the cycle count of the inside) so it would make sense for *zero* loops to be *zero* cycles.

However since this behavior is not documented anywhere I am refraining from labeling this a bug without the approval of at least one other user.

If anyone has any ideas of how they might want the cycle counting to be different or has a defense of the current system comments are welcome.

[TIO-j3xkpv79]: https://tio.run/##SypKzMzTTctJzP7/v1pDs/b///@6KQA "Brain-Flak – Try It Online"

**Comment by rahirn** [comment]
I think counting a skipped loop counting as 1 cycle is the correct behavior. 

Reason 1:   
If you had a program that was a few million `{()}`s long it would take a long time to run. If they each count as 0 cycles the whole program might take a minute to run, but report 0 cycles. That seems weird.

Reason 2:   
`{()}` would translate to something like `int a = 0; while(a != 0){do something}` in C. I would expect the `while` to take a non-zero number of CPU cycles. Therefore Brain-Flak should take a non-zero number of cycles to run `{()}`

**Comment by Wheatwizard** [comment]
I see what you are saying.  I think if the skipped loop is counted 1 is still the wrong number.  I think it should probably cost two if anything.  Each successive loop costs 2 additional cycles so it would make more sense to have the *zeroth* loop cost the same number of cycles.

**Comment by Wheatwizard** [comment]
Since there seems to be no disagreement I am going to close this issue and push the changes to master.
